name: Generar KML

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generar:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: pip install -r requirements.txt

      - name: Ejecutar script
        env:
          FIRMS_MAP_KEY: ${{ secrets.FIRMS_MAP_KEY }}
        run: python generar_kml.py

      - name: Subir KML generado
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Generar KML automático
